# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane only builds for debug config and outputs ipa"
  lane :buildOnly do
    build_app(
      configuration: "Debug",
      scheme: "FastLaneTestProject",
      silent: false,
      clean: true,
      output_name: "FastLaneTestProject.ipa",       
      sdk: "iOS 14.5",
      export_method: "development"
    )
  end

desc "Deploy ipa to DeployGate"
lane :myDeployGate do |options|
  deploygate(
  api_token: options[:deployGateKey],
  user: "sangy05",
  ipa: "./FastLaneTestProject.ipa",
  message: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
)
end
end
